window.DRILL_DATABASE = [
  {
    id: "drill_001",
    number: "01",
    category: "Defense",
    name: "Reading the Hitter",
    source: "Coach Library",
    players: "6-12",
    time: 15,
    level: "Intermediate",
    skills: "Blocking, Reading, Defense",
    purpose: "Train blockers and defenders to read the attacker’s body cues instead of only watching the ball.",
    setup: "Place a coach or hitter at the net. Blockers start at the net and back-row defenders begin in base defense.",
    run: [
      "Coach or hitter attacks to different zones.",
      "Blockers identify the hitting lane and press over the net.",
      "Defenders read the attacker and adjust around the block.",
      "Progress from controlled attacks to live swings."
    ],
    coaching: "Teach the eye sequence: ball, setter, hitter approach, hitting arm. Reward correct reads even when the dig is not perfect.",
    evaluate: "Footwork, timing, block positioning, defensive reads, and hand penetration.",
    custom: false
  },
  {
    id: "drill_002",
    number: "02",
    category: "Serve Receive",
    name: "Serve & Pass Wash",
    source: "Coach Library",
    players: "8-16",
    time: 20,
    level: "All levels",
    skills: "Serving, Passing, Communication",
    purpose: "Build game-like serve receive reps under pressure.",
    setup: "Servers line up on one side. Passers set up in serve receive with a target or setter at the net.",
    run: [
      "Server delivers a tough in-bounds serve.",
      "Passers communicate and pass to target.",
      "Score the pass quality from poor to perfect.",
      "Rotate servers and passers after each round."
    ],
    coaching: "Serve aggressively but keep the ball in. Passers should hold posture, angle the platform, and communicate seams early.",
    evaluate: "Passing accuracy, serve pressure, seam communication, and consistency.",
    custom: false
  },
  {
    id: "drill_003",
    number: "03",
    category: "Competition",
    name: "Queen / King of the Court",
    source: "Coach Library",
    players: "9-18",
    time: 20,
    level: "All levels",
    skills: "Competing, Communication, All-Around Play",
    purpose: "Create fast competitive reps with changing teammates and pressure to stay on the court.",
    setup: "Use teams of 2 or 3. One side is the queen/king side and challengers rotate in from the other side.",
    run: [
      "Challengers initiate with a serve, toss, or free ball.",
      "Winner of the rally moves to or stays on the queen/king side.",
      "Losing team rotates off.",
      "Play for time or to a target score."
    ],
    coaching: "Keep the pace high. This drill is great for evaluating communication, adaptability, and competitiveness.",
    evaluate: "Effort, communication, ball control, ability to win points, and teamwork with changing groups.",
    custom: false
  },
  {
    id: "drill_004",
    number: "04",
    category: "Ball Control",
    name: "Pepper Progression",
    source: "Coach Library",
    players: "Pairs",
    time: 10,
    level: "Beginner",
    skills: "Passing, Setting, Controlled Attacking",
    purpose: "Warm up while building basic ball-control rhythm.",
    setup: "Pair players 10-15 feet apart with one ball per pair.",
    run: [
      "Start with pass-set-catch or pass-set-pass control.",
      "Progress to dig-set-roll shot.",
      "Add one-touch pepper for advanced groups.",
      "Add movement before each contact."
    ],
    coaching: "Players should call the ball, face the target, and prioritize control over power.",
    evaluate: "Platform control, hand setting, communication, and ability to keep the ball alive.",
    custom: false
  },
  {
    id: "drill_005",
    number: "05",
    category: "Setting",
    name: "Setter Accuracy Test",
    source: "Coach Library",
    players: "Individual",
    time: 10,
    level: "Intermediate",
    skills: "Setting, Footwork, Conditioning",
    purpose: "Evaluate setter accuracy and consistency under movement and fatigue.",
    setup: "Place setter at the target area with a feeder and a setting target.",
    run: [
      "Setter starts low or seated, then moves into position.",
      "Setter delivers to a target zone.",
      "Repeat for a timed round or set number of reps.",
      "Track accurate sets."
    ],
    coaching: "Focus on clean hands, balanced feet, and a repeatable release point.",
    evaluate: "Accuracy, footwork, conditioning, balance, and consistency.",
    custom: false
  },
  {
    id: "drill_006",
    number: "06",
    category: "Serving",
    name: "Serving Targets / Zones",
    source: "Coach Library",
    players: "Any",
    time: 15,
    level: "All levels",
    skills: "Serving, Accuracy, Strategy",
    purpose: "Improve serving accuracy to specific zones and seams.",
    setup: "Place targets in deep zones and short seams. Servers begin behind the end line.",
    run: [
      "Players serve a set number of balls.",
      "Award points for hitting called zones.",
      "Track missed serves separately.",
      "Add pressure by requiring makes in a row."
    ],
    coaching: "Build a consistent toss and routine. Players should serve aggressively without giving away easy errors.",
    evaluate: "Serve accuracy, consistency, ability to hit zones, and serving under pressure.",
    custom: false
  },
  {
    id: "drill_007",
    number: "07",
    category: "Serve Receive",
    name: "Triangle Serve Receive",
    source: "Coach Library",
    players: "3-6",
    time: 15,
    level: "Intermediate",
    skills: "Passing, Seams, Communication",
    purpose: "Train three-player serve receive communication and seam responsibility.",
    setup: "Three passers form a receive triangle. Servers are across the net with a target at the net.",
    run: [
      "Serve into seams between passers.",
      "Passers call early and pass to target.",
      "Rotate passing positions after each round.",
      "Increase tempo with multiple servers when ready."
    ],
    coaching: "The earliest loud call wins. Define seam rules before the drill starts.",
    evaluate: "First step, communication, seam ownership, and pass quality.",
    custom: false
  },
  {
    id: "drill_008",
    number: "08",
    category: "Attacking",
    name: "Approach & Swing Lines",
    source: "Coach Library",
    players: "Any",
    time: 15,
    level: "All levels",
    skills: "Hitting, Footwork, Timing",
    purpose: "Groove approach footwork, timing, and arm swing mechanics.",
    setup: "Hitters line up at the pin. Coach or setter delivers balls.",
    run: [
      "Hitters approach and swing to a called zone.",
      "Alternate line and cross-court swings.",
      "Progress from tossed balls to live sets.",
      "Add targets or a blocker as players improve."
    ],
    coaching: "Approach should be late and fast. Emphasize high contact and full arm swing.",
    evaluate: "Footwork, timing, contact point, shot control, and swing mechanics.",
    custom: false
  },
  {
    id: "drill_009",
    number: "09",
    category: "Team Systems",
    name: "Coverage & Transition Wash",
    source: "Coach Library",
    players: "12+",
    time: 20,
    level: "Advanced",
    skills: "Coverage, Transition, Team Defense",
    purpose: "Train players to cover hitters and transition quickly from defense to offense.",
    setup: "Run full 6v6 with coach-entered balls.",
    run: [
      "Coach enters a ball to start the rally.",
      "Team attacks and immediately covers the hitter.",
      "Continue the rally through transition situations.",
      "Use wash scoring to reward consecutive execution."
    ],
    coaching: "Players must collapse into coverage, then release quickly into transition.",
    evaluate: "Coverage position, transition speed, team organization, and rally consistency.",
    custom: false
  },
  {
    id: "drill_010",
    number: "10",
    category: "Defense",
    name: "Defense vs. Live Hitting",
    source: "Coach Library",
    players: "6-12",
    time: 15,
    level: "Intermediate",
    skills: "Digging, Defense, Reading",
    purpose: "Give defenders repeated reps against live or controlled attacks.",
    setup: "Place hitters or coaches at the net. Defenders start in base positions with a setter target.",
    run: [
      "Attack balls to assigned defensive zones.",
      "Defenders dig to target.",
      "Rotate defenders through each position.",
      "Mix in tips and roll shots."
    ],
    coaching: "Stop feet before contact, stay low, angle the platform, and pursue every ball.",
    evaluate: "Defensive reads, platform control, pursuit, and dig-to-target accuracy.",
    custom: false
  }
,
  {
    id: "drill_011",
    number: "11",
    category: "Team Systems",
    name: "Free Ball to Attack",
    source: "Coach Library",
    players: "6-12",
    time: 15,
    level: "All levels",
    skills: "Passing, Setting, Hitting, Transition",
    purpose: "Teach the team to recognize an easy free ball and turn it into an organized attack.",
    setup: "Coach stands across the net with balls. Receiving team sets up in base or free-ball formation.",
    run: [
      "Coach sends a free ball over the net.",
      "Players call free ball early and pass to the setter area.",
      "Setter runs the offense and hitters take full approaches.",
      "Score only clean conversions or kills."
    ],
    coaching: "Free balls should become scoring chances. Demand early communication, clean first contact, and aggressive transition footwork.",
    evaluate: "Free-ball communication, pass quality, setter decision, hitter readiness, and attack conversion.",
    custom: false
  },
  {
    id: "drill_012",
    number: "12",
    category: "Ball Control",
    name: "Butterfly Drill",
    source: "Coach Library",
    players: "6-12",
    time: 15,
    level: "Beginner",
    skills: "Serving, Passing, Setting, Movement",
    purpose: "Create a continuous serve-pass-set rotation that gives every player repeated contacts.",
    setup: "Set up serving, passing, setting, and target/shag positions in a rotation loop.",
    run: [
      "Player serves and follows the serve to the passing line.",
      "Passer passes to the setter or target.",
      "Setter sets to target, then rotates into shag or serve position.",
      "Keep the pattern moving with minimal stopping."
    ],
    coaching: "Keep the pace quick but controlled. Every contact should have a target and purpose.",
    evaluate: "Serve consistency, passing platform, movement, setting touch, and ability to rotate roles.",
    custom: false
  },
  {
    id: "drill_013",
    number: "13",
    category: "Defense",
    name: "Middle Blocker Footwork",
    source: "Coach Library",
    players: "Any",
    time: 12,
    level: "Intermediate",
    skills: "Blocking, Footwork, Timing",
    purpose: "Train middle blockers to move laterally, close space, and press over the net.",
    setup: "Middle blockers start at the net. Coach or hitter is positioned at either pin.",
    run: [
      "Middle moves from base to the called side.",
      "Use shuffle or crossover footwork depending on distance.",
      "Blocker jumps and presses over the net.",
      "Alternate left and right sides."
    ],
    coaching: "Square the hips before jumping. Hands should press over the net, not just reach straight up.",
    evaluate: "Footwork, balance, timing, hand penetration, and ability to close to the pin.",
    custom: false
  },
  {
    id: "drill_014",
    number: "14",
    category: "Setting",
    name: "Setter Transition",
    source: "Coach Library",
    players: "2-6",
    time: 12,
    level: "Intermediate",
    skills: "Setting, Transition, Footwork",
    purpose: "Train the setter to release from base and beat the ball to the target area.",
    setup: "Setter begins in defensive base. Coach feeds pass-quality balls to different locations.",
    run: [
      "Coach feeds a ball that forces setter movement.",
      "Setter releases to the net or target zone.",
      "Setter delivers a hittable ball to the pin or middle.",
      "Vary the feed location and set option."
    ],
    coaching: "Setter must move early, arrive balanced, and square to the target before release.",
    evaluate: "Release speed, footwork, balance, set location, and decision-making.",
    custom: false
  },
  {
    id: "drill_015",
    number: "15",
    category: "Setting",
    name: "Out-of-System Setting",
    source: "Coach Library",
    players: "3-6",
    time: 12,
    level: "Advanced",
    skills: "Setting, Ball Control, Out-of-System Play",
    purpose: "Practice delivering hittable balls when the first contact pulls the team out of system.",
    setup: "Use a passer, setter, and hitter. Coach sends difficult balls to force off-target passes.",
    run: [
      "Coach sends a tough ball to the passer.",
      "Setter chases the ball and delivers a high, hittable set.",
      "Hitter adjusts and attacks safely.",
      "Rotate passers, setters, and hitters."
    ],
    coaching: "When out of system, high to the pin is usually the safest answer. A controlled bump set is acceptable.",
    evaluate: "Composure, chase footwork, set height, hitter adjustment, and keeping the rally playable.",
    custom: false
  },
  {
    id: "drill_016",
    number: "16",
    category: "Defense",
    name: "Pursuit / Emergency Defense",
    source: "Coach Library",
    players: "4-12",
    time: 12,
    level: "Intermediate",
    skills: "Digging, Pursuit, Effort",
    purpose: "Build hustle, emergency movement, and the habit of keeping difficult balls alive.",
    setup: "Coach has balls at the net. Defenders begin in the back court.",
    run: [
      "Coach tips, rolls, or drives balls into open space.",
      "Defenders sprint, sprawl, or run through the ball to keep it alive.",
      "Add a setter target so the save must be playable.",
      "Score effort and successful saves."
    ],
    coaching: "Players must read early and go now. Reward effort, body control, and balls kept playable.",
    evaluate: "Pursuit speed, emergency technique, effort, court awareness, and playable saves.",
    custom: false
  },
  {
    id: "drill_017",
    number: "17",
    category: "Team Systems",
    name: "Serve Receive to Attack",
    source: "Coach Library",
    players: "12",
    time: 20,
    level: "Advanced",
    skills: "Passing, Setting, Hitting, Sideout",
    purpose: "Train first-ball offense from serve receive through a full attack.",
    setup: "Run 6v6. One side serves and the receiving side runs its serve-receive pattern.",
    run: [
      "Server initiates with a tough serve.",
      "Receiving team passes, sets, and attacks.",
      "Play the rally out after the first attack.",
      "Rotate through all six rotations."
    ],
    coaching: "A clean pass creates offensive options. Track sideout success by rotation.",
    evaluate: "Pass quality, first-ball attack, rotation alignment, communication, and sideout efficiency.",
    custom: false
  },
  {
    id: "drill_018",
    number: "18",
    category: "Attacking",
    name: "Down-Ball Hitting Repetition",
    source: "Coach Library",
    players: "Any",
    time: 12,
    level: "Beginner",
    skills: "Hitting, Contact, Shot Control",
    purpose: "Build clean swing mechanics through high-repetition controlled attacks.",
    setup: "Hitters line up at the pin or middle. Coach tosses consistent balls.",
    run: [
      "Hitter swings at a controlled toss or set.",
      "Aim to specific target zones.",
      "Rotate quickly for high reps.",
      "Progress from standing swings to short approaches."
    ],
    coaching: "One cue at a time: high elbow, contact in front, fast arm, controlled finish.",
    evaluate: "Contact point, arm swing, shot accuracy, consistency, and ability to adjust.",
    custom: false
  },
  {
    id: "drill_019",
    number: "19",
    category: "Defense",
    name: "Two-Person Defense",
    source: "Coach Library",
    players: "Pairs",
    time: 12,
    level: "Intermediate",
    skills: "Defense, Reading, Communication",
    purpose: "Give two defenders repeated read-and-dig reps while owning the seam between them.",
    setup: "Two defenders start in the back court. Coach attacks from across the net or from a box.",
    run: [
      "Coach attacks at or between the two defenders.",
      "Defenders call the ball and dig to target.",
      "Reset to base after each contact.",
      "Mix hard-driven balls with tips."
    ],
    coaching: "Stop before contact and angle the platform to target. Seam communication must be early.",
    evaluate: "Reading, platform control, recovery, seam ownership, and communication.",
    custom: false
  },
  {
    id: "drill_020",
    number: "20",
    category: "Competition",
    name: "Serving Under Pressure",
    source: "Coach Library",
    players: "Any",
    time: 10,
    level: "All levels",
    skills: "Serving, Mental Toughness, Pressure",
    purpose: "Train servers to keep their routine and make serves when pressure increases.",
    setup: "Servers line up behind the end line. Add a visible target or team goal.",
    run: [
      "Players must make a set number of serves in a row.",
      "A miss resets the count.",
      "Progress from in-bounds serves to called zones.",
      "Add conditioning before the serve for fatigue pressure."
    ],
    coaching: "The routine matters. Breathe, reset, repeat the same toss, and do not rush after a miss.",
    evaluate: "Serve consistency, composure, target accuracy, and routine under pressure.",
    custom: false
  }
];
